# This is a basic workflow to help you get started with Actions

name: CI/CD-Tests-github-Dmokrite

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    timeout-minutes: 2
    strategy:
      matrix:
        # Les différents OS sur lesquels faire tourner les actions
        os: [ubuntu-latest]
        # Les différentes version de node
        node: [20, 18, 16]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Install node on the machine
      - uses: actions/setup-node@v4
        with:
          # version de node définit dans la matrice test dynamiquement
          node-version: ${{ matrix.node }}
          # Install node V20
          # node-version: 20
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      # Stocke le chemin du store de PNPM en variable d'environnement
      #- name: Get pnpm store directory
        #shell: bash
        #run: |
          #echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
          
      - run: pnpm i
      - run: node -v
      - run: pnpm -v
      - run: pnpm lint
      - run: pnpm test
  deploy:
    runs-on: unbuntu-latest
    # vérifie qu'on est sur la branch main
    if: github.ref == 'refs/heads/main'
    needs: build
    steps:
      - uses: actions/checkout@v3
      - run: npm publish
        env:
          # créer un compte sur npm pour générer un token (voir screen discord)
          NODE_AUTH_TOKEN: 010101
      #- uses: actions/setup-node@v4
        #with:
          #node-version: '20.x'
          #registry-url: 'https://npm.pkg.github.com'
