# This is a basic workflow to help you get started with Actions

name: CI/CD Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    strategy:
      matrix:
        # Les différents OS sur lesquels faire tourner les actions
        os: [ubuntu-latest, ubuntu-20.04, windows-2022]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Install node on the machine
      - uses: actions/setup-node@v4
        with:
          # Install node V20
          node-version: 20
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - run: pnpm i
      - run: node -v
      - run: pnpm -v
      - run: pnpm lint
      - run: pnpm test


